####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                                                                              | #
# |                                                                                              | #
# |     â–‘â–‘â–‘â–‘â–‘â–‘        â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–‘â–‘â–‘â–‘â–ˆâ–ˆâ•—â–‘â–‘â–‘â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•—â–ˆâ–ˆâ•—â–‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—        â–‘â–‘â–‘â–‘â–‘â–‘             | #
# |     â–‘â–‘â–‘â–‘â–‘â–‘        â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–‘â–‘â–‘â–ˆâ–ˆâ•‘â–‘â–‘â–‘â–ˆâ–ˆâ•‘â•šâ•â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–‘â–‘â–‘â–‘â–‘â–ˆâ–ˆâ•”â•â•â•â•â•        â–‘â–‘â–‘â–‘â–‘â–‘             | #
# |     â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—        â–ˆâ–ˆâ•‘â–‘â–‘â•šâ•â•â–‘â–‘â–‘â–ˆâ–ˆâ•‘â–‘â–‘â–‘â–ˆâ–ˆâ•‘â–‘â–‘â–‘â–ˆâ–ˆâ•‘â–‘â–‘â–‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–‘â–‘â–‘â–‘â–‘â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–‘        â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—             | #
# |     â•šâ•â•â•â•â•        â–ˆâ–ˆâ•‘â–‘â–‘â–ˆâ–ˆâ•—â–‘â–‘â–‘â–ˆâ–ˆâ•‘â–‘â–‘â–‘â–ˆâ–ˆâ•‘â–‘â–‘â–‘â–ˆâ–ˆâ•‘â–‘â–‘â–‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–‘â–‘â–‘â–‘â–‘â–‘â•šâ•â•â•â–ˆâ–ˆâ•—        â•šâ•â•â•â•â•             | #
# |     â–‘â–‘â–‘â–‘â–‘â–‘        â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•—â•šâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•â–‘â–‘â–‘â–ˆâ–ˆâ•‘â–‘â–‘â–‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â•        â–‘â–‘â–‘â–‘â–‘â–‘             | #
# |     â–‘â–‘â–‘â–‘â–‘â–‘        â–‘â•šâ•â•â•â•â•â–‘â•šâ•â•â–‘â•šâ•â•â•â•â•â•â–‘â–‘â–‘â–‘â•šâ•â•â–‘â–‘â–‘â•šâ•â•â•šâ•â•â•â•â•â•â•â•šâ•â•â•â•â•â•â–‘        â–‘â–‘â–‘â–‘â–‘â–‘             | #
# |                                                                                              | #
# |                         ğ˜¼ ğ™¥ğ™§ğ™–ğ™©ğ™ğ™˜ğ™–ğ™¡, ğ™¨ğ™šğ™˜ğ™ªğ™§ğ™š ğ™¥ğ™¡ğ™ªğ™œğ™ğ™£ ğ™©ğ™¤ ğ™¢ğ™–ğ™ ğ™š ğ™®ğ™¤ğ™ªğ™§ ğ™¡ğ™ğ™›ğ™š ğ™šğ™–ğ™¨ğ™ğ™šğ™§.                        | #
# |                                                                                              | #
# |                                Â© 2023 - Powered by me.imcj                                   | #
# |                                                                                              | #
# |                                                                                              | #
# |  Para um melhor entendimento deste arquivo acesse nossa documentaÃ§Ã£o:                        | #
# |   ==> https://return-3.gitbook.io/cchat/                                                     | #
# |                                                                                              | #
# |  Local para definir ou desativar funÃ§Ãµes.                                                    | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# Ãrea designada para desativa ou ativar funÃ§Ãµes,
# padrÃµes do Plugin.

# Ãrea de Menus
# ----

Bigorna:
  habilitado: true

Craft:
  habilitado: true

EChest:
  habilitado: true

# Ãrea de comandos de AdministraÃ§Ã£o
# ----

InvSee:
  habilitado: true

Vanish:
  habilitado: true

Voar:
  habilitado: true

Sudo:
  habilitado: true


Luz:
  habilitado: true

# Utilidades
# ----

Ping:
  habilitado: true

Cores:
  habilitado: true

Chapeu:
  habilitado: true

Helloworldcmd:
  habilitado: false